package com.part.computer.model

import com.part.computer.R

object PartOfData {
    val dummyTheParts = listOf(
        thePart(1, R.drawable.reward_1, "Processor", 5000,"Processor CPU, atau Central Processing Unit, adalah salah satu bagian terpenting dalam perangkat keras komputer. Ini berfungsi sebagai otak komputer, menangani instruksi dan tugas pemrosesan data. Processor CPU yang efisien memungkinkan kinerja komputer yang cepat dan responsif. Keberhasilan sebagian besar aplikasi dan tugas komputasi bergantung pada kemampuan processor untuk mengeksekusi perintah dengan efisien."),
        thePart(2, R.drawable.reward_2, "GPU Card", 10000, "GPU, atau Graphics Processing Unit, atau Kartu Grafis, adalah komponen yang bertanggung jawab untuk mengolah dan merender grafis pada layar komputer. GPU khusus digunakan untuk meningkatkan kinerja grafis, sangat penting untuk permainan, desain grafis, dan tugas pemrosesan grafis lainnya. Kartu Grafis modern sering dilengkapi dengan teknologi canggih untuk memberikan pengalaman visual yang optimal."),
        thePart(3, R.drawable.reward_3, "RAM", 1000, "RAM, atau Random Access Memory, adalah tipe memori sistem yang menyimpan data sementara untuk memungkinkan akses cepat oleh processor. RAM memberikan ruang kerja tambahan untuk aplikasi dan sistem operasi, memastikan kinerja yang lancar dan responsif. Kapasitas dan kecepatan RAM memainkan peran kunci dalam kinerja sistem secara keseluruhan."),
        thePart(4, R.drawable.reward_4, "SSD", 3000, "Penyimpanan SSD, atau Solid State Drive, adalah perangkat penyimpanan data yang menggunakan teknologi flash memory untuk menyimpan informasi. SSD menawarkan kecepatan baca dan tulis yang tinggi, membuat booting sistem operasi dan loading aplikasi menjadi lebih cepat. Selain itu, SSD tidak memiliki bagian bergerak, sehingga lebih tahan terhadap guncangan dan lebih efisien secara energi dibandingkan dengan hard drive konvensional."),
        thePart(5, R.drawable.reward_5, "Motherboard", 6500, "Motherboard adalah papan sirkuit utama dalam sistem komputer yang menghubungkan berbagai komponen perangkat keras. Ini menyediakan jalur komunikasi antara processor, RAM, kartu grafis, dan komponen lainnya. Motherboard menentukan kompatibilitas dan ketersediaan port eksternal, memainkan peran penting dalam fungsionalitas dan upgradeabilitas sistem."),
        thePart(6, R.drawable.reward_6, "Power Supply", 100, "Power Supply Unit (PSU) adalah komponen yang menyediakan daya listrik untuk semua komponen perangkat keras dalam sistem komputer. PSU mengubah daya listrik dari sumber daya listrik menjadi bentuk yang dapat digunakan oleh komputer. Keandalan dan kapasitas daya PSU penting untuk menjaga stabilitas sistem dan mencegah masalah daya."),
        thePart(7, R.drawable.reward_7, "Cooling System", 500, "Cooling System atau Sistem Pendingin adalah komponen yang menjaga suhu optimal dalam sistem komputer. Ini mencakup kipas, heatsink, dan sistem pendingin cair (water cooling) untuk mendinginkan processor, kartu grafis, dan komponen lainnya. Suhu yang terkendali membantu mencegah overheating dan memastikan kinerja yang stabil."),
        thePart(8, R.drawable.reward_8, "Network Card", 150, "Network Interface Card (NIC) adalah kartu yang memungkinkan komputer terhubung ke jaringan. NIC mendukung koneksi ke internet, jaringan lokal (LAN), atau jaringan lainnya. Kecepatan dan jenis koneksi NIC dapat memengaruhi kecepatan transfer data dan kinerja jaringan."),
        thePart(9, R.drawable.reward_9, "Sound Card", 1500, "Sound Card adalah kartu ekspansi yang memungkinkan komputer menghasilkan suara. Ini penting untuk mendukung audio dalam permainan, multimedia, dan aplikasi kreatif lainnya. Sound Card modern sering dilengkapi dengan fitur audio berkualitas tinggi untuk meningkatkan pengalaman mendengarkan."),
        thePart(10, R.drawable.reward_10, "Monitor", 3500, "Monitor adalah perangkat output yang menampilkan informasi visual dari komputer. Resolusi, ukuran layar, dan teknologi tampilan (seperti IPS atau OLED) memainkan peran penting dalam kualitas gambar yang ditampilkan. Monitor yang baik meningkatkan pengalaman visual pengguna."),
        thePart(11, R.drawable.reward_11, "Keyboard", 2500, "Keyboard Mekanikal menggunakan sakelar mekanikal untuk setiap tombol, memberikan respons taktis dan umur pemakaian yang lebih lama. Keyboard ini populer di kalangan pengguna yang membutuhkan ketepatan dan kenyamanan saat mengetik."),
        thePart(12, R.drawable.reward_12, "Mouse Gaming", 1400, "Mouse Gaming dirancang khusus untuk kebutuhan permainan, dengan sensitivitas tinggi, jumlah tombol yang dapat diprogram, dan desain ergonomis. Mouse ini membantu pemain untuk memiliki kontrol yang presisi dalam permainan."),
    )
}